### ISSUE TITLE
Object data_el in share_file_with_link missing attribute name

### ISSUE THREAD

**Issue by cterence** [owncloud/pyocclient#253]
When I try to use the function `share_file_with_link` including the file path as  the only argument, the function errors out with this message :

```
line 910, in share_file_with_link
'name': data_el.find('name').text
AttributeError: 'NoneType' object has no attribute 'text'
```

It seems that the object `data_el` misses its name property, which I don't want to provide as an argument to the function.
The only way to make my code work with this function is to comment line 910.
It would be nice to be able to use this function without having to name the shared link.

**Comment by drego85** [comment]
Are you using pyocclient with NextCloud?

**Comment by cterence** [comment]
Yes

**Comment by drego85** [comment]
Ok, from Pyocclient version 0.5 support for ownCloud 8.1, 9.0 and 9.1 has been removed.

I believe this also leads to problems for NextCloud. Pyocclient is developed for Owncloud not for Nextcloud.

I recommend you install Pyocclient version 0.4, it works perfectly with Nextcloud.

**Comment by cterence** [comment]
Alright that was the right call, my app works with pyocclient v0.4 ! Thank you
